language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t choijihyeok/docker-fullstack-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true choijihyeok/docker-fullstack-app npm run test

after_success:
  - docker build -t choijihyeok/docker-frontend ./frontend
  - docker build -t choijihyeok/docker-backend ./backend
  - docker build -t choijihyeok/docker-nginx ./nginx

  - docker logout
  
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push choijihyeok/docker-frontend
  - docker push choijihyeok/docker-backend
  - docker push choijihyeok/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app-2"
  env: "docker-fullstack-app-2-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-939992775538
  bucker_path: "docker-fullstack-app-2"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY