language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t Crete666/docker-fullstack-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true Crete666/docker-fullstack-app npm run test

after_success:
  - docker build -t choijihyeok/docker-frontend ./frontend
  - docker build -t choijihyeok/docker-backend ./backend
  - docker build -t choijihyeok/nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push choijihyeok/docker-frontend
  - docker push choijihyeok/docker-backend
  - docker push cchoijihyeok/nginx-nginx