language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -f ./frontend/Dockerfile.dev ./frontend -t choijihyeok:/docker-fullstack-app

script:
  - docker run -e CI=true choijihyeok:/docker-fullstack-app npm run test

after_success:
  - docker build ./frontend -t choijihyeok/docker-frontend
  - docker build ./backend -t choijihyeok/docker-backend
  - docker build ./nginx -t choijihyeok/nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push choijihyeok/docker-frontend
  - docker push choijihyeok/docker-backend
  - docker push cchoijihyeok/nginx ./nginx