version: "2.4"
services:
  frontend:
    image: choijihyeok/docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem limit: 128m

  nginx: 
    restart: always
    image: choijihyeok/docker-nginx
    ports: 
      - "80:80"
    mem limit: 128m
    links:
      - frontend
      - backend

  backend:
    image: choijihyeok/docker-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: docker-fullstack-mysql.c4sp8fmwqfrc.ap-northeast-2.rds.amazonaws.com
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: choijihyeok
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306
    mem limit: 128m